databases:
  - name: schedule_app_db
    region: singapore
    plan: free
    databaseName: django
    user: amaritsu
services:
  - type: web
    name: schedule_app_web
    env: docker
    dockerfilePath: "dockerfiles/render/Dockerfile"
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schedule_app_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
