previewsEnabled: true
previewsExpireAfterDays: 3
databases:
  - name: six1_template_db
    region: singapore
    plan: starter
    databaseName: django
    user: six1
services:
  - type: web
    name: six1_template_web
    env: docker
    dockerfilePath: "dockerfiles/render/Dockerfile"
    region: singapore
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: six1_template_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
